another symptomatic fix for app==null in AppUpdateStatus
Log:
 0 D: Writing unhandled exception to: /data/user/0/eu.bubu1.fdroidclassic/files/1.1-beta3-1608913315352.tracedroid
1 D: current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
file: /data/user/0/eu.bubu1.fdroidclassic/files/1.1-beta3-1608913317640.tracedroid
Android Version: 8.1.0
Phone Model: Nexus 5X
TraceDroid Version: 1.1
TraceDroid extra:
Stacktrace:
 java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.fdroid.fdroid.data.App.name' on a null object reference
	at org.fdroid.fdroid.AppUpdateStatusManager.getAppErrorIntent(AppUpdateStatusManager.java:480)
	at org.fdroid.fdroid.AppUpdateStatusManager.setEntryContentIntentIfEmpty(AppUpdateStatusManager.java:449)
	at org.fdroid.fdroid.AppUpdateStatusManager.updateApkInternal(AppUpdateStatusManager.java:257)
	at org.fdroid.fdroid.AppUpdateStatusManager.updateApk(AppUpdateStatusManager.java:352)
	at org.fdroid.fdroid.data.InstalledAppProviderService.onHandleWork(InstalledAppProviderService.java:208)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more